substitutions:
  name: espcontrol-jc8012p4a1-d0b737
  friendly_name: Espcontrol 10inch

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  setup:
    url: https://github.com/jtenniswood/espcontrol/
    file: devices/guition-esp32-p4-jc8012p4a1/packages.yaml
    refresh: 1sec
