// =============================================================================
// GENERATED WEB MODEL - do not edit by hand
// Generated by scripts/build.py from src/webserver/model/index.ts.
// =============================================================================
"use strict";
var EspControlModel = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // src/webserver/model/index.ts
  var index_exports = {};
  __export(index_exports, {
    CARD_CONFIG_FIELDS: () => CARD_CONFIG_FIELDS,
    applySpans: () => applySpans,
    backLabelFromOrder: () => backLabelFromOrder,
    backOrderToken: () => backOrderToken,
    backupOrderUsedSlots: () => backupOrderUsedSlots,
    backupPlaceSlotAt: () => backupPlaceSlotAt,
    buildSubpageGrid: () => buildSubpageGrid,
    cardConfigChanged: () => cardConfigChanged,
    clearSpans: () => clearSpans,
    cloneCardConfig: () => cloneCardConfig,
    copyCardConfig: () => copyCardConfig,
    coveredCells: () => coveredCells,
    decodeConfigField: () => decodeConfigField,
    emptyCardConfig: () => emptyCardConfig,
    encodeConfigField: () => encodeConfigField,
    isBackOrderToken: () => isBackOrderToken,
    legacyButtonConfigSafe: () => legacyButtonConfigSafe,
    markSpannedCells: () => markSpannedCells,
    parseBackOrderToken: () => parseBackOrderToken,
    parseGridOrder: () => parseGridOrder,
    parseRawButtonConfig: () => parseRawButtonConfig,
    parseSubpageOrder: () => parseSubpageOrder,
    planBackupButtonLayout: () => planBackupButtonLayout,
    serializeGridOrder: () => serializeGridOrder,
    serializeSubpageGrid: () => serializeSubpageGrid,
    sizeColSpan: () => sizeColSpan,
    sizeFitsAt: () => sizeFitsAt,
    sizeFromToken: () => sizeFromToken,
    sizeRowSpan: () => sizeRowSpan,
    sizeToken: () => sizeToken,
    subpageOrderForSerialize: () => subpageOrderForSerialize,
    trimConfigFields: () => trimConfigFields
  });

  // src/webserver/model/card.ts
  var CARD_CONFIG_FIELDS = [
    "entity",
    "label",
    "icon",
    "icon_on",
    "sensor",
    "unit",
    "type",
    "precision",
    "options"
  ];
  function emptyCardConfig(type) {
    return {
      entity: "",
      label: "",
      icon: "Auto",
      icon_on: "Auto",
      sensor: "",
      unit: "",
      type: type || "",
      precision: "",
      options: ""
    };
  }
  function cloneCardConfig(src) {
    const button = {
      entity: src?.entity || "",
      label: src?.label || "",
      icon: src?.icon || "Auto",
      icon_on: src?.icon_on || "Auto",
      sensor: src?.sensor || "",
      unit: src?.unit || "",
      type: src?.type || "",
      precision: src?.precision || "",
      options: src?.options || ""
    };
    if (src && Object.prototype.hasOwnProperty.call(src, "_whenOnActive")) {
      button._whenOnActive = src._whenOnActive;
    }
    if (src && Object.prototype.hasOwnProperty.call(src, "_whenOnMode")) {
      button._whenOnMode = src._whenOnMode;
    }
    return button;
  }
  function copyCardConfig(target, src) {
    const button = cloneCardConfig(src);
    for (const field of CARD_CONFIG_FIELDS) {
      target[field] = button[field];
    }
    target._whenOnActive = button._whenOnActive;
    target._whenOnMode = button._whenOnMode;
    return target;
  }
  function cardConfigChanged(before, after) {
    for (const field of CARD_CONFIG_FIELDS) {
      if ((before[field] || "") !== (after[field] || "")) return true;
    }
    return false;
  }
  function trimConfigFields(fields) {
    while (fields.length > 1 && !fields[fields.length - 1]) fields.pop();
    return fields;
  }
  function encodeConfigField(value) {
    return String(value || "").replace(/[%,;|:]/g, (ch) => {
      const hex = ch.charCodeAt(0).toString(16).toUpperCase();
      return "%" + (hex.length < 2 ? "0" : "") + hex;
    });
  }
  function decodeConfigField(value) {
    return String(value || "").replace(/%([0-9a-fA-F]{2})/g, (_match, hex) => {
      return String.fromCharCode(parseInt(hex, 16));
    });
  }
  function legacyButtonConfigSafe(fields) {
    return fields.join(";").charAt(0) !== "~" && fields.every((field) => {
      return String(field || "").indexOf(";") < 0;
    });
  }
  function parseRawButtonConfig(value) {
    const compact = !!(value && value.charAt(0) === "~");
    const parts = compact ? value.substring(1).split(",") : (value || "").split(";");
    const decoded = compact ? parts.map(decodeConfigField) : parts;
    return {
      entity: decoded[0] || "",
      label: decoded[1] || "",
      icon: decoded[2] || "Auto",
      icon_on: decoded[3] || "Auto",
      sensor: decoded[4] || "",
      unit: decoded[5] || "",
      type: decoded[6] || "",
      precision: decoded[7] || "",
      options: decoded[8] || ""
    };
  }

  // src/webserver/model/grid.ts
  function copySizes(sizes) {
    return { ...sizes || {} };
  }
  function sizeFromToken(token) {
    return token === "d" ? 2 : token === "w" ? 3 : token === "b" ? 4 : token === "t" ? 5 : token === "x" ? 6 : 1;
  }
  function sizeToken(size) {
    return size === 4 ? "b" : size === 2 ? "d" : size === 3 ? "w" : size === 5 ? "t" : size === 6 ? "x" : "";
  }
  function sizeRowSpan(size) {
    return size === 5 ? 3 : size === 2 || size === 4 ? 2 : 1;
  }
  function sizeColSpan(size) {
    return size === 6 ? 3 : size === 3 || size === 4 ? 2 : 1;
  }
  function coveredCells(pos, size, _maxSlots, gridCols, includeOrigin) {
    const cells = [];
    const rowSpan = sizeRowSpan(size);
    const colSpan = sizeColSpan(size);
    for (let r = 0; r < rowSpan; r += 1) {
      for (let c = 0; c < colSpan; c += 1) {
        if (!includeOrigin && r === 0 && c === 0) continue;
        cells.push(pos + r * gridCols + c);
      }
    }
    return cells;
  }
  function sizeFitsAt(pos, size, maxSlots, gridCols) {
    if (pos < 0 || pos >= maxSlots || gridCols <= 0) return false;
    const col = pos % gridCols;
    const row = Math.floor(pos / gridCols);
    const rows = Math.ceil(maxSlots / gridCols);
    return col + sizeColSpan(size) <= gridCols && row + sizeRowSpan(size) <= rows && pos + (sizeRowSpan(size) - 1) * gridCols + sizeColSpan(size) - 1 < maxSlots;
  }
  function markSpannedCells(grid, pos, size, maxSlots, gridCols) {
    const cells = coveredCells(pos, size, maxSlots, gridCols, false);
    for (const cell of cells) {
      if (cell >= 0 && cell < maxSlots) grid[cell] = -1;
    }
  }
  function applySpans(grid, sizes, maxSlots, gridCols) {
    for (let i = 0; i < maxSlots; i += 1) {
      const slot = grid[i] ?? 0;
      if (!(slot > 0 || slot === -2)) continue;
      const slotKey = String(slot);
      const size = sizes[slotKey] || 1;
      if (size <= 1) continue;
      if (!sizeFitsAt(i, size, maxSlots, gridCols)) {
        delete sizes[slotKey];
        continue;
      }
      const toReserve = coveredCells(i, size, maxSlots, gridCols, false);
      let ok = true;
      for (const cell of toReserve) {
        const displaced = grid[cell] ?? 0;
        if (displaced > 0 || displaced === -2) {
          let placed = false;
          for (let j = 0; j < maxSlots; j += 1) {
            if ((grid[j] ?? 0) === 0 && toReserve.indexOf(j) === -1) {
              grid[j] = displaced;
              placed = true;
              break;
            }
          }
          if (!placed) {
            ok = false;
            break;
          }
          grid[cell] = 0;
        }
      }
      if (!ok) {
        delete sizes[slotKey];
        continue;
      }
      for (const cell of toReserve) grid[cell] = -1;
    }
  }
  function parseGridOrder(order, maxSlots, gridCols, initialSizes) {
    const grid = Array(maxSlots).fill(0);
    const sizes = copySizes(initialSizes);
    if (!order || !order.trim()) return { grid, sizes };
    const parts = order.split(",");
    for (let i = 0; i < parts.length && i < maxSlots; i += 1) {
      const value = (parts[i] || "").trim();
      if (!value) continue;
      const last = value.charAt(value.length - 1);
      const parsedSize = sizeFromToken(last);
      const slot = parseInt(value, 10);
      if (slot >= 1 && slot <= maxSlots && !Number.isNaN(slot)) {
        grid[i] = slot;
        if (parsedSize > 1) sizes[String(slot)] = parsedSize;
      }
    }
    applySpans(grid, sizes, maxSlots, gridCols);
    return { grid, sizes };
  }
  function serializeGridOrder(grid, sizes) {
    let last = -1;
    for (let i = grid.length - 1; i >= 0; i -= 1) {
      if ((grid[i] ?? 0) > 0) {
        last = i;
        break;
      }
    }
    if (last < 0) return "";
    return grid.slice(0, last + 1).map((slot) => {
      if (slot <= 0) return "";
      return String(slot) + sizeToken(sizes[String(slot)]);
    }).join(",");
  }
  function clearSpans(grid, maxSlots) {
    for (let i = 0; i < maxSlots; i += 1) {
      if (grid[i] === -1) grid[i] = 0;
    }
  }

  // src/webserver/model/backup.ts
  function backupOrderUsedSlots(order, importedCount) {
    const parts = String(order || "").split(",");
    const usedSlots = [];
    const seen = {};
    for (const part of parts) {
      const token = part.trim();
      if (!token) continue;
      const lastCh = token.charAt(token.length - 1);
      const parsedSize = sizeFromToken(lastCh);
      const num = parseInt(token, 10);
      if (Number.isNaN(num) || num < 1 || num > importedCount || seen[String(num)]) continue;
      seen[String(num)] = true;
      usedSlots.push({ oldSlot: num, size: parsedSize });
    }
    return { usedSlots, seen };
  }
  function backupPlaceSlotAt(grid, slot, pos, size, maxSlots, gridCols) {
    grid[pos] = slot;
    if (size > 1) {
      markSpannedCells(grid, pos, size, maxSlots, gridCols);
    }
  }
  function planBackupButtonLayout(sourceButtons, buttonOrder, targetSlots, gridCols) {
    const importedCount = sourceButtons.length;
    const buttons = [];
    const importedSizes = {};
    const slotMap = {};
    let orderStr = "";
    if (importedCount !== targetSlots) {
      const orderInfo = backupOrderUsedSlots(buttonOrder, importedCount);
      const usedSlots = orderInfo.usedSlots;
      const seen = orderInfo.seen;
      for (let j = 0; j < importedCount; j += 1) {
        const slotNum = j + 1;
        if (seen[String(slotNum)]) continue;
        const button = sourceButtons[j] || emptyCardConfig();
        if (button.entity || button.label || button.type) {
          usedSlots.push({ oldSlot: slotNum, size: 1 });
        }
      }
      const limit = Math.min(usedSlots.length, targetSlots);
      for (let u = 0; u < limit; u += 1) {
        const newSlot = u + 1;
        const used = usedSlots[u];
        if (!used) continue;
        slotMap[String(used.oldSlot)] = newSlot;
        buttons.push(cloneCardConfig(sourceButtons[used.oldSlot - 1] || emptyCardConfig()));
        if (used.size > 1) importedSizes[String(newSlot)] = used.size;
      }
      for (let fill = limit; fill < targetSlots; fill += 1) {
        buttons.push(emptyCardConfig());
      }
      const newGrid = Array(targetSlots).fill(0);
      let pos = 0;
      for (let p = 0; p < limit && pos < targetSlots; p += 1) {
        const newSlot = p + 1;
        let targetSize = importedSizes[String(newSlot)] || 1;
        if (!sizeFitsAt(pos, targetSize, targetSlots, gridCols)) {
          targetSize = 1;
          delete importedSizes[String(newSlot)];
        }
        backupPlaceSlotAt(newGrid, newSlot, pos, targetSize, targetSlots, gridCols);
        pos += 1;
        while (pos < targetSlots && newGrid[pos] === -1) pos += 1;
      }
      orderStr = serializeGridOrder(newGrid, importedSizes);
    } else {
      for (let i = 0; i < targetSlots; i += 1) {
        buttons.push(cloneCardConfig(i < importedCount ? sourceButtons[i] : emptyCardConfig()));
        slotMap[String(i + 1)] = i + 1;
      }
      orderStr = String(buttonOrder || "");
    }
    return {
      importedCount,
      buttons,
      button_order: orderStr,
      importedSizes,
      slotMap
    };
  }

  // src/webserver/model/subpage.ts
  var BACK_TOKENS = /* @__PURE__ */ new Set(["B", "Bd", "Bw", "Bb", "Bt", "Bx"]);
  function isBackOrderToken(token) {
    return BACK_TOKENS.has(String(token || ""));
  }
  function parseBackOrderToken(value) {
    const raw = String(value || "").trim();
    const eq = raw.indexOf("=");
    const token = eq >= 0 ? raw.substring(0, eq) : raw;
    const label = eq >= 0 ? decodeConfigField(raw.substring(eq + 1)) : "Back";
    if (!BACK_TOKENS.has(token)) {
      return { token: raw, label: "Back" };
    }
    return { token, label: label || "Back" };
  }
  function backOrderToken(baseToken, label) {
    const token = parseBackOrderToken(baseToken).token;
    const text = label || "Back";
    return text === "Back" ? token : token + "=" + encodeConfigField(text);
  }
  function backLabelFromOrder(order) {
    for (const item of order || []) {
      const parsed = parseBackOrderToken(item);
      if (BACK_TOKENS.has(parsed.token)) {
        return parsed.label || "Back";
      }
    }
    return "Back";
  }
  function parseSubpageOrder(orderStr) {
    const order = [];
    let backLabel = "Back";
    if (orderStr) {
      const parts = orderStr.split(",");
      for (const part of parts) {
        const parsed = parseBackOrderToken(part);
        order.push(parsed.token);
        if (BACK_TOKENS.has(parsed.token)) {
          backLabel = parsed.label || "Back";
        }
      }
    }
    return { order, backLabel };
  }
  function subpageOrderForSerialize(order, backLabel) {
    const out = [];
    for (const item of order || []) {
      const parsed = parseBackOrderToken(item);
      if (BACK_TOKENS.has(parsed.token)) {
        out.push(backOrderToken(parsed.token, backLabel || parsed.label || "Back"));
      } else {
        out.push(parsed.token);
      }
    }
    return out;
  }
  function buildSubpageGrid(subpage, maxSlots, gridCols) {
    const grid = Array(maxSlots).fill(0);
    const sizes = { ...subpage.sizes || {} };
    const order = subpage.order || [];
    const buttonCount = (subpage.buttons || []).length;
    if (order.length > 0) {
      const hasBack = order.some((item) => isBackOrderToken(parseBackOrderToken(item).token));
      if (hasBack) {
        for (let i = 0; i < order.length && i < maxSlots; i += 1) {
          const token = parseBackOrderToken(order[i]).token;
          if (!token) continue;
          if (isBackOrderToken(token)) {
            grid[i] = -2;
            const backSize = sizeFromToken(token.charAt(1));
            if (backSize > 1) sizes[String(-2)] = backSize;
            else delete sizes[String(-2)];
            continue;
          }
          const last = token.charAt(token.length - 1);
          const parsedSize = sizeFromToken(last);
          const slot = parseInt(token, 10);
          if (slot >= 1 && slot <= buttonCount && !Number.isNaN(slot)) {
            grid[i] = slot;
            if (parsedSize > 1) sizes[String(slot)] = parsedSize;
          }
        }
      } else {
        grid[0] = -2;
        delete sizes[String(-2)];
        for (let i = 0; i < order.length && i + 1 < maxSlots; i += 1) {
          const token = parseBackOrderToken(order[i]).token;
          if (!token) continue;
          const last = token.charAt(token.length - 1);
          const parsedSize = sizeFromToken(last);
          const slot = parseInt(token, 10);
          if (slot >= 1 && slot <= buttonCount && !Number.isNaN(slot)) {
            grid[i + 1] = slot;
            if (parsedSize > 1) sizes[String(slot)] = parsedSize;
          }
        }
      }
    } else {
      grid[0] = -2;
      delete sizes[String(-2)];
    }
    applySpans(grid, sizes, maxSlots, gridCols);
    return { grid, sizes };
  }
  function serializeSubpageGrid(grid, sizes, backLabel) {
    let last = -1;
    for (let i = grid.length - 1; i >= 0; i -= 1) {
      const slot = grid[i] ?? 0;
      if (slot > 0 || slot === -2) {
        last = i;
        break;
      }
    }
    if (last < 0) return [];
    const order = [];
    for (let i = 0; i <= last; i += 1) {
      const slot = grid[i] ?? 0;
      if (slot === -2) {
        order.push(backOrderToken("B" + sizeToken(sizes[String(-2)]), backLabel || "Back"));
      } else if (slot <= 0) {
        order.push("");
      } else {
        order.push(String(slot) + sizeToken(sizes[String(slot)]));
      }
    }
    return order;
  }
  return __toCommonJS(index_exports);
})();
